# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      r: release
    - os: osx
      r: release

r_packages:
  - covr
  - pkgdown

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'if(!requireNamespace("miniCRAN")) install.packages("miniCRAN"); if(!requireNamespace("igraph")) install.packages("igraph"); if(!requireNamespace("ggnetwork")) install.packages("ggnetwork"); if(!requireNamespace("intergraph")) install.packages("intergraph");'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
