# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      r: release
    - os: osx
      r: release

r_packages:
  - covr
  - pkgdown
  - spelling
  - miniCRAN
  - igraph
  - ggnetwork
  - intergraph

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'spelling::spell_check_setup(vignettes = TRUE, error = FALSE)'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
