# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_script:
  - Rscript -e 'remotes::install_cran(c("devtools", "covr", "spelling"))'

r:
  - oldrel
  - devel
  - release
os:
  - linux
matrix:
  include:
    - r: release
      os: osx

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'spelling::spell_check_package(vignettes = TRUE)'
