# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_script:
  - Rscript -e 'remotes::install_cran(c("devtools", "covr", "pkgdown", "spelling", "miniCRAN", "igraph", "ggnetwork", "intergraph"))'
  - Rscript -e 'remotes::install_github("ropensci/rotemplate")'

r:
  - oldrel
  - devel
os:
  - linux
matrix:
  include:
    - r: release
      os: osx
    - r: release
      os: linux
      env: DEPLOY=true

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'spelling::spell_check_package(vignettes = TRUE)'

deploy:
  - provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
    on:
      branch: master
      condition: "$DEPLOY = true"
