# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_script:
  - Rscript -e 'remotes::install_cran(c("devtools", "covr", "pkgdown", "spelling", "miniCRAN", "igraph", "ggnetwork", "intergraph"))'

matrix:
  include:
    - os: linux
      r: release
    - os: osx
      r: release

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'spelling::spell_check_package(vignettes = TRUE)'

before_deploy: Rscript -e 'remotes::install_github("ropensci/rotemplate")'
deploy:
  - provider: script
    script: Rscript -e 'pkgdown::deploy_site_github()'
    skip_cleanup: true
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
